version: '3.9'

services:
  shepherd:
    build: .
    container_name: shepherd_app
    volumes:
      - .:/app
    environment:
      - ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1.5g
        reservations:
          memory: 512m
