services:
  shepherd:
    build: .
    container_name: shepherd_app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 6g
        reservations:
          cpus: '1.0'
          memory: 2g
